apiVersion: apps/v1
kind: Deployment

metadata:
  name: todo-frontend
  labels:
    app: multi-services
    type: frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-services
      type: frontend
  template:
    metadata:
      labels:
        app: multi-services
        type: frontend
    spec:
      containers:
        - name: todo-frontend
          image: todo-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "100m"
