apiVersion: v1
kind: Service

metadata:
  name: todo-redis-headless
  namespace: {{ .Values.namespace }}
  labels:
    app: multi-services

spec:
  clusterIP: None
  selector:
    app: multi-services
    type: cache
  ports:
    - port: 6379
